### ISSUE TITLE
Chat Suggestion: Mute Feature

### ISSUE THREAD

**Issue by Twilight-Shimmer** [Rylius/CardsAgainstEquestria#145]
Even now as I type this a few immature 16 year old brats are spamming the chat on Card Against Equestria chat, with huge font text saying things like "This is our site now" or "This is our game now" or "We F*** poinies" <i purposely filtered that> 

The Following is just ONE screen shot of some of their spam. 
![screen](https://cloud.githubusercontent.com/assets/19780189/15826327/222da040-2bd5-11e6-9b29-80983f0478bd.jpg)

So here is my suggestion. Add a feature that allows is to Mute or Hide a Player from chat so we do not have to watch them spam the chat with things that distract and or disrupt gameplay and or already ongoing conversations.

**Comment by Rylius** [comment]
Muting people is part of this issue: https://github.com/Rylius/CardsAgainstEquestria/issues/113
(I'll close this one, feel free to subscribe to the other one)

I'm aware of the situation, but I don't have a lot of time to deal with this. I'll try to at least implement muting and possibly a way of reporting these people over the next few days.

**Comment by Twilight-Shimmer** [comment]
Thanks!
