### ISSUE TITLE
Allow custom set watermarks to be edited

### ISSUE THREAD

**Issue by tjhorner** [Rylius/CardsAgainstEquestria#149]
This has been a request from a few users as I was playing some games, they've asked if I could add that as a feature on CAH Creator. Right now, it's hardcoded into CAE with the "Custom" watermark. I have an issue open at CAHCreator/cah-creator#3 with the validations in place to prevent abuse.

All CAE would need to do is take the `watermark` field from CAH Creator when it requests it and then convert non-alphanumeric characters into HTML entities (to prevent XSS, of course). Or I could make a `safe_watermark` field to make it easier :)

Shouldn't be too hard.

**Comment by Rylius** [comment]
I'll stick to the watermark field and run validation on the CAE side of things just to be sure :)

**Comment by tjhorner** [comment]
Alright, sounds good! I'll get started on that when I get home then.

**Comment by Rylius** [comment]
https://github.com/Rylius/CardsAgainstEquestria/commit/568c7446cf860a8e09e73ab27348f5762ce14d5e

I've cleaned up the code responsible for loading decks, and it allows for the watermark to be set on the CAH Creator deck (not individual cards), with a maximum length of 12.

**Comment by tjhorner** [comment]
CAH Creator now sends the `watermark` field in API responses. I limited it to 12 characters on CAH Creator as well.

**Comment by Rylius** [comment]
Changes deployed
