### ISSUE TITLE
Impossible to connect

### ISSUE THREAD

**Issue by shobu13** [Rylius/CardsAgainstEquestria#155]
Hello, when i try to connect on the website, I have an error message like "internal error, try again", it's normal ?

**Comment by Rylius** [comment]
I don't see any errors in the log file - I'll need a screenshot of the error message
What exactly are you trying to do and what browser are you using?

**Comment by shobu13** [comment]
I use Firefox and first, i load the website, then, I enter a username and click on "log in", after that, the website ask to enter a password, i enter it, and the error spawn.
http://hpics.li/bd2811d
http://hpics.li/1070d3a
http://hpics.li/442663a
http://hpics.li/578c7a7

**Comment by Rylius** [comment]
I am only running cardsagainstequestria.com, I can't help you with other sites, sorry.

The French translation is here: https://github.com/juju2143/CardsAgainstEquestria
Try asking there.

**Comment by shobu13** [comment]
No problem thanks you
